date_format = "%m%d%H%M"
messages_dir = "messages"
mime_time_format = "%a, %d %b %Y %H:%M:%S +0000"
good_login = "te5t0w.t@yandex.ru"
good_password = "qFz4f9LpyUn7R23j"
recipient = "r.sakaevv@gmail.com"